apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: api
  labels:
    app: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrytgl5512.azurecr.io/poi:1.0
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sql-connection
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-connection
              key: password
        - name: SQL_SERVER
          value: 'sqlservertgl5512.database.windows.net'
        - name: SQL_DBNAME
          value: 'mydrivingDB'
        - name: ASPNETCORE_ENVIRONMENT
          value: 'Development'        