apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: api
  labels:
    app: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrytgl5512.azurecr.io/poi:1.0
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: vault-db-creds-secret
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vault-db-creds-secret
              key: password
        - name: SQL_SERVER
          value: 'sqlservertgl5512.database.windows.net'
        - name: SQL_DBNAME
          value: 'mydrivingDB'
        - name: ASPNETCORE_ENVIRONMENT
          value: 'Development'
        volumeMounts:
            - name: 'azure-kvname-user-msi'
              mountPath: '/mnt/secrets-store'
              readOnly: true
      volumes:
        - name: azure-kvname-user-msi
          csi:
            driver: 'secrets-store.csi.k8s.io'
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'azure-kvname-user-msi' 