# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: api
spec:
  provider: azure
  secretObjects:
    - secretName: vault-db-creds-secret
      type: Opaque
      data:
        - objectName: username # References dbUsername below
          key: username # Key within k8s secret for this value
        - objectName: password
          key: password
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: 50b620d7-853e-4e52-80ff-1cf40ed4d278   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: aksopenhack-secrets        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: username
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: password
          objectType: secret
          objectVersion: ""
    tenantId: 3b32d1f3-a199-413a-9ead-f881b7c8656c                # The tenant ID of the key vault