apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  labels:
    app: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registrytgl5512.azurecr.io/tripviewer:latest
        env:
        - name: TRIPS_API_ENDPOINT
          value: 'trips-service'
        - name: USERPROFILE_API_ENDPOINT
          value: 'user-service'